---
name: swagger_cd_creation_action
runner_type: "python-script"
description: Create swagger CD job from jira
enabled: true
entry_point: 'swagger_cd_creation_action.py'
parameters:
  issue_key:
    description: jira issue key
    required: true
    type: string